# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vision.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'vision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvision.proto\x12\tvision.v1\"k\n\x0ePredictRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\nimage_data\x18\x02 \x01(\x0cH\x00\x12\x13\n\timage_url\x18\x03 \x01(\tH\x00\x12\x10\n\x08\x66ilename\x18\x04 \x01(\tB\x08\n\x06source\"\x0f\n\rHealthRequest\"\xae\x01\n\x0fPredictResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07problem\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\t\x12\x10\n\x08severity\x18\x04 \x01(\t\x12\x16\n\x0erecommendation\x18\x05 \x01(\t\x12\x13\n\x0b\x65xplanation\x18\x06 \x01(\t\x12\x14\n\x0crepair_steps\x18\x07 \x03(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\t\"\x8d\x01\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x14\n\x0cmodel_loaded\x18\x04 \x01(\x08\x12 \n\x18\x62inary_classifier_loaded\x18\x05 \x01(\x08\x12\x11\n\ttimestamp\x18\x06 \x01(\t2\x95\x01\n\rVisionService\x12@\n\x07Predict\x12\x19.vision.v1.PredictRequest\x1a\x1a.vision.v1.PredictResponse\x12\x42\n\x0bHealthCheck\x12\x18.vision.v1.HealthRequest\x1a\x19.vision.v1.HealthResponseB-\n\x15\x63om.wahakun.vision.v1P\x01\xaa\x02\x11WahaKun.Vision.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.wahakun.vision.v1P\001\252\002\021WahaKun.Vision.V1'
  _globals['_PREDICTREQUEST']._serialized_start=27
  _globals['_PREDICTREQUEST']._serialized_end=134
  _globals['_HEALTHREQUEST']._serialized_start=136
  _globals['_HEALTHREQUEST']._serialized_end=151
  _globals['_PREDICTRESPONSE']._serialized_start=154
  _globals['_PREDICTRESPONSE']._serialized_end=328
  _globals['_HEALTHRESPONSE']._serialized_start=331
  _globals['_HEALTHRESPONSE']._serialized_end=472
  _globals['_VISIONSERVICE']._serialized_start=475
  _globals['_VISIONSERVICE']._serialized_end=624
# @@protoc_insertion_point(module_scope)
